prerelease: false
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: |
  $TITLE [PR #$NUMBER] @$AUTHOR
  - $BODY
no-changes-template: 'No changes'
change-title-escapes: '\<*_&'
template: |
  # What's Changed

  $CHANGES

  ###### Previous Tag: $PREVIOUS_TAG
autolabeler:
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
      - '/enhancement\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
      - '/patch\/.+/'
      - '/issue\/.+/'
    title:
      - '/fix/i'
  - label: 'documentation'
    branch:
      - '/docs\/.+/'
      - '/doc\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
exclude-labels:
  - 'chore'
  - 'skip-changelog'
  - 'no-terraform'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
      - 'hotfix'
      - 'patch'
      - 'issue'
      - 'documentation'
      - 'docs'
      - 'doc'
  default: minor
# categories:
#   - title: 'â— Breaking'
#     labels:
#       - 'breaking'
#   - title: 'Features'
#     labels:
#       - 'feature'
#       - 'enhancement'
#   - title: 'Bug Fixes'
#     labels:
#       - 'bug'
#       - 'fix'
#       - 'bugfix'
#       - 'hotfix'
#       - 'patch'
#       - 'issue'
#   - title: 'Documentation'
#     label:
#       - 'documentation'
#       - 'docs'
#       - 'doc'
