name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: 'No changes'
change-title-escapes: '\<*_&'
autolabeler:
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
      - '/enhancement\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
      - '/patch\/.+/'
      - '/issue\/.+/'
    title:
      - '/fix/i'
  - label: 'documentation'
    branch:
      - '/docs\/.+/'
      - '/doc\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
categories:
  - title: 'â— Breaking'
    labels:
      - 'breaking'
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
      - 'hotfix'
      - 'patch'
      - 'issue'
  - title: 'Documentation'
    label:
      - 'documentation'
      - 'docs'
      - 'doc'
exclude-labels:
  - 'chore'
  - 'skip-changelog'
  - 'no terraform'
prerelease: false
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
      - 'hotfix'
      - 'patch'
      - 'issue'
      - 'documentation'
      - 'docs'
      - 'doc'
  default: minor
template: |
  # What's Changed

  $CHANGES

  ###### Previous Tag: $PREVIOUS_TAG
