name: 'Auto-approver'

on:
  pull_request_target:
    branches:
      - 'main'

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'chore') == true
    steps:
      - name: 'Approve a PR'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'Enable auto-merge for Dependabot PRs'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'Notify about failure'
        if: failure()
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.CI_GH_PAT_REPO_DISPATCH_API_AUTH }}
          event-type: slack-notification
          client-payload: '{ "type": "alert", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "color": "#FF0000", "title": "‚ö†Ô∏è ${{ github.repository }}", "message": "Dependapprover failed to merge the PR ${{github.event.pull_request.html_url}}" }'
      - name: 'Notify about success'
        if: success()
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.CI_GH_PAT_REPO_DISPATCH_API_AUTH }}
          event-type: slack-notification
          client-payload: '{ "type": "build", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "color": "#2EB67D", "title": "üöß ${{ github.repository }}", "message": "Dependapprover merged the PR ${{github.event.pull_request.html_url}} for you" }'
