name: "Linter"

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  all_in_one_linter:
    name: "All-in-one"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: "Set Job Vars"
        id: vars
        run: |
          echo "task_version=$(cat ${{ github.workspace }}/.tool-versions | grep -w task | cut -d ' ' -f2)" >> $GITHUB_OUTPUT
      - name: 'Install asdf dependencies'
        uses: asdf-vm/actions/setup@v3
      - name: 'Install Task'
        uses: arduino/setup-task@v2
        with:
          version: ${{ steps.vars.outputs.task_version }}
      - name: 'Lint'
        id: lint
        run: |
          set -e
          task lint
          task docker:lint
